import type { PublicIdeaRecord } from './types';

export const AI_IDEAS: PublicIdeaRecord[] = [
  {
    id: 'build-or-buy',
    title: 'Build or Buy',
    kind: 'software',
    category: 'AI-native experiments',
    era: '2024–2026',
    status: 'AI show / invention-development format',
    summary: 'An improvisational invention format where an AI can either “buy” an idea or choose “build” and keep transforming it with the inventor until the idea becomes compelling enough to buy.',
    problem: 'Typical AI feedback either flatters ideas or critiques them once; it rarely turns evaluation into an iterative game with a clear pressure to improve.',
    evolution: 'Developed as a custom-GPT/show format mixing invention critique, entertainment, humor, and iterative product design.',
    highlights: [
      'BUILD is not rejection; it means keep evolving the idea.',
      'The system is designed to challenge rather than merely praise the inventor.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'ai-world-builder',
    title: 'Conversation-Built AI Game World',
    kind: 'software',
    category: 'AI-native experiments',
    era: '2023–2024',
    status: 'early AI-game concept',
    summary: 'A web game where AI text/audio conversations dynamically create assets, quests, NPC behavior, crafting, resources, and environmental outcomes from what players say and do.',
    problem: 'Traditional games can only react through content and rules authored in advance.',
    evolution: 'Explored chat-generated assets and outcomes, inventory/resource systems, AI quests, NPC interaction, and dynamic environments in web technologies.',
    highlights: ['One of the earlier attempts to make conversation itself an engine for world generation.'],
    evidence: 'conversation history',
  },
  {
    id: 'ai-book-game',
    title: 'Collaborative AI Book-Writing Game',
    kind: 'writing',
    category: 'AI-native experiments',
    era: '2023',
    status: 'early generative-creation concept',
    summary: 'A collaborative game in which people and AI build a book/story together while generated images summarize or visualize the evolving narrative.',
    problem: 'Writing tools usually separate text creation from visual feedback and collaborative play.',
    evolution: 'Explored treating co-writing as a game loop instead of a blank document with an AI assistant.',
    highlights: ['Text and generated visual summary were part of the same creative cycle.'],
    evidence: 'conversation history',
  },
  {
    id: 'ai-creature-cards',
    title: 'AI Creature Card Game',
    kind: 'visual',
    category: 'AI-native experiments',
    era: '2023',
    status: 'generative-game concept',
    summary: 'A creature/card system where AI generates unique creatures, visual identity, stats, abilities, and possible evolution rather than drawing from a fixed card library.',
    problem: 'Collectible games are constrained by finite authored sets and repeated assets.',
    evolution: 'Explored AI-generated creatures, evolution, digital play, and possible physical-card expansion.',
    highlights: ['The collectible object itself could be newly generated rather than selected from a catalog.'],
    evidence: 'conversation history',
  },
  {
    id: 'mars-trainer',
    title: 'M.A.R.S. / Adaptive Skill Trainer',
    kind: 'software',
    category: 'AI-native experiments',
    era: '2023',
    status: 'game-training concept',
    summary: 'A standalone skill-training system inspired by game replay analysis, using diverse challenges and AI recognition of player inputs to train timing, accuracy, and mechanics.',
    problem: 'Watching replay analysis explains mistakes but does not always turn them into focused, adaptive practice.',
    evolution: 'Expanded from replay analysis toward an adaptive training game with real-time feedback, difficulty changes, and progression tracking.',
    highlights: ['The system turns detected weaknesses into playable training rather than passive advice.'],
    evidence: 'conversation history',
  },
];
