import type { PublicIdeaRecord } from './types';

export const CORE_IDEAS: PublicIdeaRecord[] = [\n  {
    id: 'twinthink-project',
    title: 'TwinThink',
    kind: 'software',
    category: 'TwinThink',
    era: '2024–present',
    status: 'active / core project',
    summary: 'A medium for giving an idea a persistent reality before the finished object exists, preserving its structure, history, evidence, lineage, and changing relationship to the people around it.',
    problem: 'Most systems preserve finished products, posts, or files. The early thought process, failed branches, evidence, and path from an idea to a real thing are usually lost.',
    evolution: 'Grew from idea-attribution and digital-twin thinking into a recursive spatial Canvas. Ideas appear as Shadows at distance, reveal continuity as you move closer, and unfold into deeper topology through semantic Z-depth.',
    highlights: [
      'Twins can preserve identity, structure, behavior, evidence, history, lineage, and unknowns.',
      'Shadows let an idea exist between total secrecy and full public disclosure.',
      'The Canvas uses X/Y for exploration and Z for semantic depth.',
      'Backing means “I want to see what happens next,” not a rating or purchase.',
      'The current product emphasizes continuity and proof of care rather than hype.',
    ],
    evidence: 'repository history',
  },

  {
    id: 'coinceit',
    title: 'CoinCeit',
    kind: 'software',
    category: 'TwinThink',
    era: '2024',
    status: 'precursor to TwinThink',
    summary: 'An idea-sharing platform focused on helping people publish, exchange, and develop concepts while retaining attribution and a record of origin.',
    problem: 'Early ideas are easy to copy, difficult to attribute, and often have no durable path from “I thought of this” to collaboration or value.',
    evolution: 'Explored cryptographic proof, creator identity, smart contracts, an idea marketplace/lottery, and ways advertising revenue could support ideas. The deeper attribution problem later evolved into TwinThink.',
    highlights: [
      'Treated ideas themselves as networked creative objects.',
      'Explored proof-of-origin and creator-controlled exchange.',
      'Established several questions TwinThink later reframed into Shadows, lineage, and progressive disclosure.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'shadow-system',
    title: 'Residual Shadows / White Paper Lens',
    kind: 'visual',
    category: 'TwinThink',
    era: '2026',
    status: 'active research direction',
    summary: 'A representation system where an idea can exist at different perceptual distances: a public Shadow proves that something is there while deeper views reveal progressively more structure.',
    problem: 'Creators are often forced to choose between total secrecy and full public disclosure.',
    evolution: 'Started with near-white residual image experiments, then expanded into viewer-specific Lens behavior, semantic disclosure, screen-to-screen viewing, and the idea that the same Twin can cast different Shadows for different viewers.',
    highlights: [
      'Near-white images were the original visual experiment, not the final security model.',
      'The deeper concept is progressive semantic disclosure rather than simple opacity.',
      'Printing became optional; the website itself became the main Shadow medium.',
      'A phone may eventually act as a second-screen Lens over the desktop Canvas.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'think-twice',
    title: 'Think Twice',
    kind: 'software',
    category: 'TwinThink',
    era: '2026',
    status: 'funding protocol concept',
    summary: 'A micro-funding layer where tiny amounts from ordinary activity accumulate into a pool that helps real human inventions move forward.',
    problem: 'Very early invention work often needs small amounts of capital before it is legible to traditional investors.',
    evolution: 'Explored retail round-ups, browser-extension rewards, and data-revenue clawback as ways to pool micro-contributions around human invention.',
    highlights: ['Core phrase: “round up to launch a human invention.”'],
    evidence: 'conversation history',
  },
  {
    id: 'blind-catalog',
    title: 'Blind Catalog',
    kind: 'software',
    category: 'TwinThink',
    era: '2026',
    status: 'market/disclosure concept',
    summary: 'A creator-controlled catalog where public previews reveal only non-enabling signals and fuller information is reached through direct links, trust, agreements, or payment.',
    problem: 'A normal searchable marketplace can force creators to expose too much while rewarding superficial browsing.',
    evolution: 'Moved from structured engineering previews and NDA/paywall concepts toward the broader Shadow Canvas and semantic-depth model.',
    highlights: [
      'No-search/direct-link discovery was explored as a way to preserve creator control.',
      'Progressive disclosure became more important than a conventional listing page.',
      'Corporate bounty zones were explored as an alternative to generic advertising.',
    ],
    evidence: 'conversation history',
  },
];
