import type { PublicIdeaRecord } from './types';

export const CREATIVE_IDEAS: PublicIdeaRecord[] = [
  {
    id: 'ideachew',
    title: 'IdeaChew',
    kind: 'visual',
    category: 'Creative worlds',
    era: '2024–2026',
    status: 'content/show concept',
    summary: 'A channel/show concept built around chewing through unusual, bad, unfinished, or provocative ideas rather than presenting every concept as a polished startup pitch.',
    problem: 'Idea content often rewards overconfidence and polished selling instead of openly exploring why concepts are weird, broken, or interesting.',
    evolution: 'Explored “unselling” ideas, an umbrella of bad ideas, scoring/evaluation formats, and connections to Build or Buy.',
    highlights: ['Treats failed or strange ideas as entertainment and learning material rather than waste.'],
    evidence: 'conversation history',
  },
  {
    id: 'zero-note',
    title: 'ZERO NOTE',
    kind: 'visual',
    category: 'Creative worlds',
    era: '2025–2026',
    status: 'film/world concept',
    summary: 'A cinematic speculative-fiction project developed through trailer writing, lyrics, Rome/Vatican imagery, and generated-video experimentation.',
    problem: 'Explore a story/world through music, visual language, and trailer-scale moments before committing to a conventional feature-film production pipeline.',
    evolution: 'Developed through songs/lyrics, trailer prompts, Rome/Vatican visual motifs, and experiments with multiple generative-video tools.',
    highlights: ['Treats music, worldbuilding, and film imagery as one design system.'],
    evidence: 'conversation history',
  },
  {
    id: 'zero-ledger',
    title: 'Zero Ledger',
    kind: 'writing',
    category: 'Creative worlds',
    era: '2024–2026',
    status: 'anime/world concept',
    summary: 'A speculative anime/worldbuilding concept developed as a rule-driven universe rather than a single isolated story premise.',
    problem: 'Create a fictional world whose systems and underlying rules can support many stories rather than one linear plot.',
    evolution: 'Preserved as part of the wider creative-IP archive; detailed canon remains separate from this public summary.',
    highlights: ['Represents the same system-building instinct found in the invention projects, applied to fiction.'],
    evidence: 'conversation history',
  },
  {
    id: 'fruit-animals',
    title: 'Fruit-Animal Documentary Universe',
    kind: 'visual',
    category: 'Creative worlds',
    era: '2025–2026',
    status: 'generative-video series',
    summary: 'A mock-nature-documentary series where fruit and animals are fused into internally consistent fictional species presented as though they naturally exist.',
    problem: 'Turn absurd visual mashups into believable worldbuilding rather than one-off random AI images.',
    evolution: 'Developed recurring species including KiwiSplice, Strawbeak, Bananaconda, Orangoose, and Grapplepede, with documentary-style presentation.',
    highlights: [
      'The rule is not simply “combine two things”; the hybrid should behave like a plausible species.',
      'Uses documentary language to sell impossible biology as ordinary reality.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'dickymouse',
    title: 'DickyMouse / the Chodehouse',
    kind: 'visual',
    category: 'Creative worlds',
    era: '2025–2026',
    status: 'parody animation concept',
    summary: 'An intentionally absurd parody animation/video concept riffing on familiar children’s-clubhouse language and structure.',
    problem: 'Use recognizable format and timing as a setup for deliberately absurd comedy.',
    evolution: 'Explored character naming, clubhouse parody, theme-song ideas, and generated-video execution.',
    highlights: ['Represents the comedic/meme side of the wider creative practice.'],
    evidence: 'conversation history',
  },
  {
    id: 'mount-ever-wrist',
    title: 'Mount Ever Wrist',
    kind: 'music',
    category: 'Music & performance',
    era: '2026',
    status: 'released/demo song + social concept',
    summary: 'A playful rap/song project built around the “Everest / wrist so cold” wordplay, later treated as material for a memeable dance/social trend.',
    problem: 'Create a track whose hook, visual language, and movement can be instantly recognizable enough to become participatory content rather than only a song upload.',
    evolution: 'The song became a test case for viral choreography ideas and later for the TwinThink question of how a piece of music could cast a Shadow without simply becoming a waveform or spectrogram.',
    highlights: [
      'Connects songwriting, meme logic, freestyle dance, and visual identity.',
      'Became one of the first candidate Music Twins for progressive disclosure experiments.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'music-twins-2026',
    title: 'Music Twins: CRHYMES / DusT / naptimesellinynim',
    kind: 'music',
    category: 'Music & performance',
    era: '2026',
    status: 'music archive / Shadow research set',
    summary: 'A group of original tracks used to test how TwinThink might represent music as a living Twin instead of reducing songs to cover art or a conventional audio player.',
    problem: 'Music is temporal and behavioral; a visual-first idea platform needs a way to preserve rhythm, structure, revisions, and identity without pretending a song is just an image.',
    evolution: 'These tracks were discussed as a dataset for experimenting with musical Shadows: rhythm, energy, vocal density, contour, sections, and progressively disclosed audio structure.',
    highlights: [
      'The goal is to show what a song is doing before necessarily revealing the full master.',
      'A music Shadow could perform visually and sonically at different semantic depths.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'self-drawing-logo',
    title: 'TwinThink Self-Drawing / Ink-Drop Logo Motion',
    kind: 'visual',
    category: 'Creative worlds',
    era: '2026',
    status: 'brand-motion system',
    summary: 'A TwinThink logo/motion concept where the mark appears to draw or generate itself, later evolving into a fluid ink-drop transition that visually explains recursive zoom.',
    problem: 'A static logo does not communicate the idea of a Twin creating, revealing, or containing another version of itself.',
    evolution: 'Moved from a self-drawing twin metaphor to ink pooling, a falling droplet, impact on a fresh mark, and eventually the navigation idea that a distant point can become a whole inner world when the camera falls into it.',
    highlights: [
      'The animation became functional product language rather than decoration.',
      'The droplet metaphor now informs TwinThink’s semantic Z-axis transitions.',
    ],
    evidence: 'mixed',
  },
];
