import type { PublicIdeaRecord } from './types';

export const ENERGY_IDEAS: PublicIdeaRecord[] = [
  {
    id: 'em-wheel',
    title: 'Electromagnetically Powered Wheel',
    kind: 'physical',
    category: 'Energy & motion',
    era: '2016 science-fair era',
    status: 'built/tested early engineering project',
    summary: 'A wheel designed to create rotation and measured forward motion through sequenced electromagnetic interaction rather than a conventional rotational motor at the wheel.',
    problem: 'Explore whether controlled electromagnetic polarity changes could directly create usable rotational motion around an axle.',
    evolution: 'Developed and tested as an early systems-engineering/science-fair project and later became part of a broader family of electromagnetic wheel, suspension, and braking ideas.',
    highlights: [
      'One of the earliest documented engineering projects in the archive.',
      'Used measured motion/testing rather than existing only as a sketch.',
      'Later concepts extended electromagnetic behavior into suspension and energy recovery.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'em-suspension',
    title: 'Electromagnetic Suspension / Three-Rimmed Wheel',
    kind: 'physical',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'archived mechanical concept',
    summary: 'A wheel and suspension family exploring independent electromagnetic suspension modules and unconventional multi-rim wheel architecture.',
    problem: 'Conventional suspension and wheel assemblies mechanically couple impact handling, wheel structure, and drive behavior.',
    evolution: 'Multiple journal pages show three-rimmed-wheel and individual-suspension drafts rather than a single frozen design.',
    highlights: [
      'Several independent suspension-module drafts are preserved.',
      'Part of the same early electromagnetic mobility lineage as the powered wheel.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'renewable-braking',
    title: 'Renewable Braking Energy',
    kind: 'physical',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'archived energy-recovery concept',
    summary: 'A vehicle-energy concept exploring recovery of energy that would otherwise be lost during braking.',
    problem: 'Deceleration normally throws useful kinetic energy away as heat.',
    evolution: 'The archive preserves top, practical, and side-view studies, indicating the idea was iterated geometrically rather than existing as a single note.',
    highlights: [
      'Three documented views survive in the invention journal.',
      'Belongs to the broader electromagnetic mobility/energy family.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'new-engine',
    title: 'New Engine / Internal Drive Concept',
    kind: 'physical',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'archived concept — mechanics not fully transcribed',
    summary: 'An early alternative engine/internal-drive concept preserved in the invention journal.',
    problem: 'Explore a different way of converting internal motion/energy into useful drive.',
    evolution: 'The surviving archive supports the title and drawing lineage more strongly than a complete transcription, so the public record intentionally does not invent missing mechanics.',
    highlights: ['Kept as an honest incomplete archival Twin rather than filling gaps with guessed engineering.'],
    evidence: 'journal archive',
  },
  {
    id: 'packaging-drone',
    title: 'Electromagnetically Operated Packaging Drone',
    kind: 'physical',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'archived drone/logistics concept',
    summary: 'A package-transport drone concept exploring electromagnetic actuation as part of the aircraft and payload-handling system.',
    problem: 'Delivery drones need efficient flight plus reliable pickup/release of physical payloads.',
    evolution: 'The archive contains both a packaging-drone drawing and separate notes, plus a related dynamic-propeller concept.',
    highlights: [
      'Designed around package logistics rather than a generic camera drone.',
      'Has a documented sibling concept: the Dynamic Propeller.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'dynamic-propeller',
    title: 'Drone Dynamic Propeller',
    kind: 'physical',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'archived aerodynamics concept',
    summary: 'A propeller concept whose geometry or behavior can adapt instead of remaining fixed across every flight condition.',
    problem: 'A fixed propeller is a compromise between lift, cruise, payload, noise, and changing air conditions.',
    evolution: 'Preserved as its own journal design and also connected conceptually to the packaging-drone project.',
    highlights: ['Explores variable/adaptive propeller behavior rather than only changing motor speed.'],
    evidence: 'journal archive',
  },
  {
    id: 'gas-expansion',
    title: 'Gaseous Combustion for Controlled Dynamic Expansion',
    kind: 'physical',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'archived actuation study',
    summary: 'An early high-impulse actuation concept studying whether controlled gas expansion could create fast mechanical movement.',
    problem: 'Some mechanisms need rapid expansion or force from a very compact source.',
    evolution: 'Preserved as a journal concept. The public Canvas intentionally keeps this at conceptual level rather than exposing construction detail.',
    highlights: ['Represents an early exploration of unusual actuation physics.'],
    evidence: 'journal archive',
  },
  {
    id: 'underwater-motion',
    title: 'Underwater “Perpetual Motion Theory”',
    kind: 'theory',
    category: 'Energy & motion',
    era: 'early journal',
    status: 'failed exploration / preserved learning',
    summary: 'A series of underwater buoyancy/gravity mechanism drafts exploring whether a repeating imbalance could create continuous motion.',
    problem: 'Investigate whether changing buoyancy around a loop could sustain useful motion.',
    evolution: 'Multiple drafts survive, including the creator’s own annotation that it “doesn’t really work.” It is intentionally preserved as a failed idea because the failure is part of the invention history.',
    highlights: [
      'At least three draft stages are represented in the archive.',
      'A good example of TwinThink preserving dead ends rather than pretending every idea succeeds.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'charger-car',
    title: 'AI-Piloted Charger Car',
    kind: 'physical',
    category: 'Energy & motion',
    era: '2024',
    status: 'mobility/energy infrastructure concept',
    summary: 'An autonomous support vehicle imagined as mobile charging infrastructure for other electric vehicles, including the possibility of energy-sharing convoys.',
    problem: 'EV charging normally requires the low-battery car to stop and find fixed infrastructure.',
    evolution: 'Explored a charger coming to the vehicle, directional energy transfer, and chains/convoys where power support moves with traffic.',
    highlights: [
      'Reverses the normal charging relationship: infrastructure moves to the car.',
      'Explored convoy behavior as a network rather than one charger serving one parked vehicle.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'electromagnet-octocopter',
    title: 'Electromagnet Octocopter',
    kind: 'physical',
    category: 'Energy & motion',
    era: '2024',
    status: 'aircraft concept',
    summary: 'A multi-rotor aircraft concept exploring electromagnetic elements alongside an octocopter architecture.',
    problem: 'Explore whether field-based actuation/control can add useful behavior to a redundant multi-rotor platform.',
    evolution: 'Preserved as an exploratory aircraft idea; detailed mechanics remain intentionally uncommitted in the public record.',
    highlights: ['Part of a recurring electromagnetic-motion lineage.'],
    evidence: 'conversation history',
  },
];
