import type { PublicIdeaRecord } from './types';

export const GAME_IDEAS: PublicIdeaRecord[] = [
  {
    id: 'kdance',
    title: 'k.dance / Motion Music',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2024–2026',
    status: 'performance-interface concept',
    summary: 'A low-latency system where full-body dance movement directly creates or controls music so the performer’s body functions like an instrument.',
    problem: 'Most music interfaces reduce bodily expression to buttons, pads, or a few tracked gestures.',
    evolution: 'Expanded from camera motion-to-MIDI into full-body mapping where direction, speed, pose, isolation, timing, and footwork can become musical structure.',
    highlights: ['Movement should cause sound directly, not navigate a menu.', 'Freestyle movement is a feature rather than forcing choreography.'],
    evidence: 'conversation history',
  },
  {
    id: 'giant-canvas',
    title: '3,000,000 × 3,000,000 Living Canvas',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2024',
    status: 'large-world interface concept',
    summary: 'An enormous persistent digital canvas where collective user behavior permanently changes the world at multiple zoom levels.',
    problem: 'Normal online spaces are page-based and disposable; they rarely let many people leave spatial, persistent traces in one shared world.',
    evolution: 'Explored huge coordinates, user trails, overlapping ripple-like effects, persistent plot changes, and zoom-dependent meaning. This is a clear ancestor of TwinThink’s current spatial Canvas.',
    highlights: ['Large-scale zoom was a recurring idea before TwinThink.', 'Interactions could spread like raindrop ripples instead of staying isolated.'],
    evidence: 'conversation history',
  },
  {
    id: 'specimen-io',
    title: 'Specimen.io',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2024',
    status: 'persistent creature-world concept',
    summary: 'A persistent world where players control evolving/customizable specimens, alter territory, cooperate, compete, build, and leave lasting changes on the map.',
    problem: 'Match-based games reset the world and erase the long-term consequences of player behavior.',
    evolution: 'Explored map-based worlds, home bases, creature skins, resource competition, alliances, tournaments, evolving creatures, and persistent ecosystem/territory change.',
    highlights: ['World state is shaped by cumulative player behavior.', 'Creature identity, geography, and economy were designed to interact rather than live in separate menus.'],
    evidence: 'conversation history',
  },
  {
    id: 'runend',
    title: 'RUNEND / The Fall',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2026',
    status: 'body-controlled game concept',
    summary: 'A continuously falling surreal experience where webcam/body movement controls flight through impossible environments.',
    problem: 'Most motion-controlled games still feel like gesture buttons; the goal here is for posture and movement to become the physics of the character directly.',
    evolution: 'Explored skydiving body lean, gesture abilities, blink detection, puppet imagery, camera deception, behavioral memory, co-op rituals, and a “fall or fly” structure.',
    highlights: ['The body is the controller without explicit button metaphors.', 'Near-miss gestures were explored so imperfect human movement still has expressive meaning.', 'The world can remember behavior instead of resetting after each encounter.'],
    evidence: 'mixed',
  },
  {
    id: 'impact',
    title: 'IMPACT',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2026',
    status: 'physics / voice-competition game concept',
    summary: 'A physics-heavy game lineage combining body-controlled movement, ragdolls, modular machines/vehicles, beat-driven systems, and eventually the simpler idea that freestyle rap itself directly affects the match.',
    problem: 'Traditional competitive games separate expression from mechanics: players press abstract action buttons instead of their actual performance becoming the mechanic.',
    evolution: 'Moved from falling/ragdoll control into buildable machines with Beatbox cores, BPM-linked abilities, proximity voice, hand-tracked locomotion, and finally toward direct rap-vs-rap interaction.',
    highlights: ['Beat can function as power/timing rather than mere soundtrack.', 'Vehicle physics, ragdoll movement, and physical components were explored as one continuous system.', 'Later simplification removed unnecessary building when it got in the way of the expressive core.'],
    evidence: 'conversation history',
  },
  {
    id: 'cypher-punk',
    title: 'Cypher Punk / ASCII City / Rap World',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2026',
    status: 'working prototype lineage',
    summary: 'A living 3D ASCII/cyberpunk city where spoken or typed rap changes the world: language is treated as a reality engine rather than flavor text.',
    problem: 'Rap games usually score lyrics after the fact instead of letting language itself create physical consequences.',
    evolution: 'Explored semantic word categories, rhyme-chain multipliers, procedural city mutation, live BPM/beatboxing, AI MCs, cypher circles, floating words, environmental reactions, and persistent landmarks.',
    highlights: ['Environment, movement, emotion, and spatial language can change different parts of the city.', 'Rhyme chains amplify the effect rather than acting only as a score.', 'North Star: rap causes the world to happen.'],
    evidence: 'mixed',
  },
  {
    id: 'sway',
    title: 'SWAY',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2026',
    status: 'voice-native rap interface concept',
    summary: 'A freestyle system where microphone input, words, rhythm, cadence, pitch, timing, and delivery directly control visual/game behavior.',
    problem: 'Speech-driven games often reduce voice to transcription and then map words onto conventional commands.',
    evolution: 'Moved through PNG-image reels, a beat-synced 1×4 visual bar, browser-extension ideas, semantic word forces, delivery-sensitive behavior, and machine prediction that tries to anticipate the rapper’s next concept.',
    highlights: ['No predetermined lyrics are required.', 'Empty beat slots can stay empty instead of AI inventing content the rapper did not say.', 'Human intuition vs machine intuition became part of the performance itself.'],
    evidence: 'mixed',
  },
  {
    id: 'cipher-roulette',
    title: 'Cipher Roulette',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2026',
    status: 'multiplayer freestyle concept',
    summary: 'A rapid anonymous voice-competition format where two freestylers enter a synchronized beat session and then rotate back into matchmaking.',
    problem: 'Online freestyle competition often loses momentum through long judging, menus, and network-delayed musical synchronization.',
    evolution: 'Explored local beat playback, peer-to-peer voice, browser audio processing, a tug-of-war momentum system, and an immediate ending that keeps the queue moving.',
    highlights: ['Designed for continuous performance rather than round-by-round score screens.', 'Local beat synchronization was preferred over server streaming to reduce perceived lag.'],
    evidence: 'conversation history',
  },
  {
    id: 'grim-terface',
    title: 'Grim-terface / Persistent Trail World',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2024',
    status: 'infinite-canvas MMO concept',
    summary: 'An infinite zoomable multiplayer world where player movement and expression leave trails that can reshape terrain, ecosystems, resources, and the visual map.',
    problem: 'Most multiplayer worlds treat movement as temporary navigation rather than a lasting creative act.',
    evolution: 'Explored prompt-customized avatars, AI-generated visuals, real-time multiplayer, persistent trails, terrain/ecosystem changes, and strategy around a giant shared canvas.',
    highlights: ['Player presence becomes world history.', 'Closely related to the later giant-canvas and TwinThink spatial-thinking lineage.'],
    evidence: 'conversation history',
  },
  {
    id: 'ar-board-game',
    title: 'AR Board Game',
    kind: 'software',
    category: 'Games & interactive systems',
    era: '2024',
    status: 'mixed-reality game concept',
    summary: 'A board-game system where a physical play surface gains a digital augmented layer rather than being replaced by a screen-only game.',
    problem: 'Digital games offer dynamic worlds while physical board games offer shared presence and tangible space; each normally sacrifices the other.',
    evolution: 'Explored using AR to let physical objects and board state become anchors for a changing digital world.',
    highlights: ['Another example of physical objects acting as interfaces to a digital layer.'],
    evidence: 'conversation history',
  },
];
