import type { PublicIdeaRecord } from './types';

export const PHYSICAL_IDEAS: PublicIdeaRecord[] = [
  {
    id: 'bubbleblock',
    title: 'BubbleBlock / BUBBLEYEBLOCK',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: '2024–2026',
    status: 'product concept / prototype direction',
    summary: 'Wearable glasses intended to reduce or obscure advertisements in the physical world instead of only blocking ads on digital screens.',
    problem: 'People can install ad blockers in browsers, but have little control over unavoidable visual advertising in streets and public environments.',
    evolution: 'Explored camera-based ad recognition, selective optical obscuring, shimmer/watermark behavior, and creator-first launch ideas. The name later evolved toward BUBBLEYEBLOCK.',
    highlights: [
      'The blocked region itself could subtly identify the product, turning an ad into anti-advertising.',
      'The system was imagined as user-selectable filtering rather than simply blacking out the whole environment.',
      'The project mixes computer vision with physical optics instead of treating AR as the only answer.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'wear-os',
    title: 'Wear O’s',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: '2024–2026',
    status: 'wearable-device concept',
    summary: 'A ring-shaped personal vaporizer concept where an ordinary-looking wearable also becomes the functional device and interface.',
    problem: 'Conventional personal devices are separate objects to carry and visually advertise their purpose.',
    evolution: 'Developed around a compact ring, a separate base/container, a clean internal air path, and separating activation from inhalation so the interaction could remain small and discreet.',
    highlights: [
      'The ring was treated as both jewelry and an active device.',
      'A separate base was explored so the ring itself could stay compact.',
      'A strong example of turning the form of an everyday object into the interface.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'resip',
    title: 'RESIP / SipSmolder',
    kind: 'physical',
    category: 'Physical inventions',
    era: '2024–present',
    status: 'canonical physical Twin #0001',
    summary: 'A reusable self-heating straw that warms a drink while it is used without requiring a cord or conventional battery in the straw.',
    problem: 'Hot drinks cool long before people finish them, while existing reheating options are usually stationary or powered.',
    evolution: 'Developed through reusable thermal storage, snap activation, segmented thermal chambers, recharge by heat, outdoor/coffee variants, and later became the canonical physical example used to test TwinThink itself.',
    highlights: [
      'Uses reusable stored heat rather than a disposable heating reaction.',
      'Explored hot-water/dishwasher recharge and modular thermal sections.',
      'Became a major test case for TwinThink BOM, behavior, evidence, history, and lineage modeling.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'smholder',
    title: 'Smholder',
    kind: 'physical',
    category: 'Physical inventions',
    era: '2024',
    status: 'thermal product concept',
    summary: 'A reusable container that stores heat and can release it later to warm food or drink without a microwave.',
    problem: 'Portable containers preserve food but usually cannot actively reheat it without external power.',
    evolution: 'Extended the same reusable thermal-storage thinking as the straw into a larger vessel, including recharging during a hot-water or dishwasher cycle.',
    highlights: [
      'Designed around heat storage rather than continuous electrical heating.',
      'Explored reclaiming otherwise-wasted heat from normal kitchen routines.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'u3dpen',
    title: 'U3dPEN',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: '2024',
    status: 'fabrication/reclaim concept',
    summary: 'A handheld additive-making pen centered on recovering and reusing unusual material rather than consuming conventional plastic filament.',
    problem: 'Desktop fabrication often creates new waste while requiring purpose-bought feedstock.',
    evolution: 'Explored ferrofluid/reclaim behavior, electromagnetic recovery, drawing modes, water-based reclaim ideas, and a 3D-pen mode. The name was partly chosen for its visual/upside-down quality.',
    highlights: [
      'Combines making and reclaiming in the same tool lineage.',
      'Treats material recovery as part of the interaction, not a separate recycling step.',
    ],
    evidence: 'conversation history',
  },
  {
    id: 'paper-3d-pen',
    title: 'Paper-Fed 3D Printer Pen',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: 'early journal',
    status: 'archived invention sketch',
    summary: 'A handheld 3D fabrication concept using paper or cellulose as the primary build material instead of standard plastic filament.',
    problem: 'Common 3D pens depend on plastic feedstock and are poorly suited to biodegradable, everyday material streams.',
    evolution: 'The journal concept explored feeding ordinary paper/cellulose into a pen that could convert it into a structural extrudable material.',
    highlights: [
      'Early sustainable-fabrication idea preserved in the invention journal.',
      'Conceptually related to later U3dPEN work but kept as a distinct archived design.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'ferropen',
    title: 'FerroPen V1 / V2',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: 'early journal',
    status: 'archived invention series',
    summary: 'A drawing/writing tool based on magnetically responsive fluid so marks can behave more dynamically than ordinary ink.',
    problem: 'Traditional ink is static and effectively irreversible once placed.',
    evolution: 'Multiple journal versions explored controlled magnetic-fluid behavior, later feeding into broader ideas about reclaimable marks and magnetic-material interfaces.',
    highlights: [
      'Two documented journal versions survive.',
      'The lineage later influenced U3dPEN/reclaim thinking.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'ferro-display',
    title: 'Ferro / Crystalline Display',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: 'early journal',
    status: 'archived display concept',
    summary: 'A display concept where information can physically move and hold shape rather than existing only as flat light on a screen.',
    problem: 'Conventional screens are visually dynamic but physically flat and untouchable.',
    evolution: 'Combined magnetically responsive display behavior with a locking/persistent material state, pointing toward tactile or low-power physical pixels.',
    highlights: [
      'Explored a screen that could be both visible and tactile.',
      'Connected magnetic-fluid experiments with persistent-state material thinking.',
    ],
    evidence: 'journal archive',
  },
  {
    id: 'xylem-camouflage',
    title: 'Xylem Thread Dynamic Camouflage',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: 'early journal → 2024',
    status: 'adaptive-material concept',
    summary: 'A textile/thread system inspired by plant fluid transport that changes its own appearance instead of relying on a permanently printed camouflage pattern.',
    problem: 'Static camouflage and static textiles cannot adapt when lighting, environment, or use context changes.',
    evolution: 'Early journal sketches later expanded into active-thread thinking involving fluid transport, responsive fiber behavior, and dynamically changing surface appearance.',
    highlights: [
      'Treats the fabric itself as an active system.',
      'Uses biological transport as inspiration for material architecture.',
      'Potential non-defense directions include performance wear and responsive climate/visual textiles.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'hologram-projector',
    title: '3D Projector Hologram',
    kind: 'visual',
    category: 'Interfaces & materials',
    era: 'early journal',
    status: 'archived spatial-display concept',
    summary: 'A display concept aimed at creating an apparent three-dimensional image in space rather than a flat image trapped on a screen.',
    problem: 'Flat displays cannot naturally preserve parallax, spatial depth, or object-like presence.',
    evolution: 'Sits in a longer lineage of phone-pyramid holograph experiments, multi-view imagery, and later TwinThink interest in device-dependent perception.',
    highlights: [
      'Early exploration of changing what information looks like depending on viewing geometry.',
      'Conceptually precedes later Shadow/Lens thinking even though the technologies are different.',
    ],
    evidence: 'mixed',
  },
  {
    id: 'arm-computer',
    title: 'Mini PC Keyboard & Trackpad + Arm Carrier',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: 'early journal',
    status: 'archived wearable-computing concept',
    summary: 'A forearm-mounted compact-computing interface combining a small keyboard and trackpad in a wearable carrier.',
    problem: 'Conventional computer input assumes a desk even when the computer itself can be portable.',
    evolution: 'An early attempt to move the workstation onto the body rather than simply shrinking a laptop.',
    highlights: ['Prefigures later interest in interfaces that disappear into clothing or ordinary objects.'],
    evidence: 'journal archive',
  },
  {
    id: 'cubli-led',
    title: 'Cubli LED Flywheel Cube',
    kind: 'physical',
    category: 'Interfaces & materials',
    era: '2024',
    status: 'kinetic display concept',
    summary: 'A reaction-wheel cube concept combining balancing/motion hardware with programmable light so the same mechanism can create movement and persistence-of-vision imagery.',
    problem: 'Robotic balancing mechanisms usually hide their motion instead of turning it into a visible output medium.',
    evolution: 'Combined Cubli-like reaction wheels with LEDs and possible axis movement to create dynamic light structures.',
    highlights: ['Mechanics and display are the same system rather than separate subsystems.'],
    evidence: 'conversation history',
  },
];
